///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SSPC_iOS
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("113daff0-e45c-4210-9244-d9147ec1a700", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SSPC_iOS_modifiedRepository repository.
        /// </summary>
        public static SSPC_iOS_modifiedRepository repo = SSPC_iOS_modifiedRepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
            Email = "jyoti.duchaniya@pentair.com";
            Passord = "Demo@123";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

        string _Email;

        /// <summary>
        /// Gets or sets the value of variable Email.
        /// </summary>
        [TestVariable("aa138557-d8c3-4273-8fca-ad65ff418680")]
        public string Email
        {
            get { return _Email; }
            set { _Email = value; }
        }

        string _Passord;

        /// <summary>
        /// Gets or sets the value of variable Passord.
        /// </summary>
        [TestVariable("8efed2d9-22ff-4c70-9c96-f168a5d1f21e")]
        public string Passord
        {
            get { return _Passord; }
            set { _Passord = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$Email' on item 'ComPentairPentairhome.Email_input'.", repo.ComPentairPentairhome.Email_inputInfo, new RecordItemIndex(0));
            repo.ComPentairPentairhome.Email_input.Element.SetAttributeValue("Text", Email);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(1));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.EnterEmailTextLogin' at Center", repo.ComPentairPentairhome.EnterEmailTextLoginInfo, new RecordItemIndex(2));
            repo.ComPentairPentairhome.EnterEmailTextLogin.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(3));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.GetStartedLogin' at Center", repo.ComPentairPentairhome.GetStartedLoginInfo, new RecordItemIndex(4));
            repo.ComPentairPentairhome.GetStartedLogin.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(5));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$Passord' on item 'ComPentairPentairhome.PassordInput'.", repo.ComPentairPentairhome.PassordInputInfo, new RecordItemIndex(6));
            repo.ComPentairPentairhome.PassordInput.Element.SetAttributeValue("Text", Passord);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(7));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.LoginUpperRight' at UpperRight", repo.ComPentairPentairhome.LoginUpperRightInfo, new RecordItemIndex(8));
            repo.ComPentairPentairhome.LoginUpperRight.Touch(Location.UpperRight);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(9));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.LOGIN' at Center", repo.ComPentairPentairhome.LOGINInfo, new RecordItemIndex(10));
            repo.ComPentairPentairhome.LOGIN.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 7s.", new RecordItemIndex(11));
            Delay.Duration(7000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
