///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SSPC_iOS
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ProductOverview recording.
    /// </summary>
    [TestModule("b8338539-7110-4909-b2b8-d819b4807a59", ModuleType.Recording, 1)]
    public partial class ProductOverview : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SSPC_iOS_modifiedRepository repository.
        /// </summary>
        public static SSPC_iOS_modifiedRepository repo = SSPC_iOS_modifiedRepository.Instance;

        static ProductOverview instance = new ProductOverview();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ProductOverview()
        {
            Nickname = "Sump Controller";
            NewNickname = "Sump controller";
            NickNameClick = "Nickname Sump Controller";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ProductOverview Instance
        {
            get { return instance; }
        }

#region Variables

        string _NewNickname;

        /// <summary>
        /// Gets or sets the value of variable NewNickname.
        /// </summary>
        [TestVariable("8f79d259-5035-4597-b6b8-26bf02d1294a")]
        public string NewNickname
        {
            get { return _NewNickname; }
            set { _NewNickname = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Nickname.
        /// </summary>
        [TestVariable("8dd48787-0af9-4924-8ff3-a0abb12ed4b0")]
        public string Nickname
        {
            get { return repo.Nickname; }
            set { repo.Nickname = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable NickNameClick.
        /// </summary>
        [TestVariable("89415c25-5f02-4c8e-ac0b-2c3cbed27277")]
        public string NickNameClick
        {
            get { return repo.NickNameClick; }
            set { repo.NickNameClick = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.HomeIcon' at Center", repo.ComPentairPentairhome.HomeIconInfo, new RecordItemIndex(0));
            repo.ComPentairPentairhome.HomeIcon.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(1));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.SSPCtileClick' at Center", repo.ComPentairPentairhome.SSPCtileClickInfo, new RecordItemIndex(2));
            repo.ComPentairPentairhome.SSPCtileClick.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(3));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.Settingsicon' at Center", repo.ComPentairPentairhome.SettingsiconInfo, new RecordItemIndex(4));
            repo.ComPentairPentairhome.Settingsicon.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(5));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.ProductOverview' at Center", repo.ComPentairPentairhome.ProductOverviewInfo, new RecordItemIndex(6));
            repo.ComPentairPentairhome.ProductOverview.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(7));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.nickname' at Center", repo.ComPentairPentairhome.nicknameInfo, new RecordItemIndex(8));
            repo.ComPentairPentairhome.nickname.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(9));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute text to '$NewNickname' on item 'ComPentairPentairhome.nicknameedit'.", repo.ComPentairPentairhome.nicknameeditInfo, new RecordItemIndex(10));
            repo.ComPentairPentairhome.nicknameedit.Element.SetAttributeValue("text", NewNickname);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(11));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.UIWindow.NicknameSave' at Center", repo.ComPentairPentairhome.UIWindow.NicknameSaveInfo, new RecordItemIndex(12));
            repo.ComPentairPentairhome.UIWindow.NicknameSave.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(13));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.DeviceUpdatedOK' at Center", repo.ComPentairPentairhome.DeviceUpdatedOKInfo, new RecordItemIndex(14));
            repo.ComPentairPentairhome.DeviceUpdatedOK.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(15));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.ChangeAddress' at Center", repo.ComPentairPentairhome.ChangeAddressInfo, new RecordItemIndex(16));
            repo.ComPentairPentairhome.ChangeAddress.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(17));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.ChangeAddressDropDown' at Center", repo.ComPentairPentairhome.ChangeAddressDropDownInfo, new RecordItemIndex(18));
            repo.ComPentairPentairhome.ChangeAddressDropDown.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(19));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.EMainStOrange' at Center", repo.ComPentairPentairhome.EMainStOrangeInfo, new RecordItemIndex(20));
            repo.ComPentairPentairhome.EMainStOrange.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(21));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.ChangeAddressContinue' at Center", repo.ComPentairPentairhome.ChangeAddressContinueInfo, new RecordItemIndex(22));
            repo.ComPentairPentairhome.ChangeAddressContinue.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(23));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.AddressUpdatedOK' at Center", repo.ComPentairPentairhome.AddressUpdatedOKInfo, new RecordItemIndex(24));
            repo.ComPentairPentairhome.AddressUpdatedOK.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(25));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.ChangeAddress' at Center", repo.ComPentairPentairhome.ChangeAddressInfo, new RecordItemIndex(26));
            repo.ComPentairPentairhome.ChangeAddress.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(27));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.ChangeAddressDropDown' at Center", repo.ComPentairPentairhome.ChangeAddressDropDownInfo, new RecordItemIndex(28));
            repo.ComPentairPentairhome.ChangeAddressDropDown.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(29));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.Container22475EMunozStQueenCreek' at Center", repo.ComPentairPentairhome.Container22475EMunozStQueenCreekInfo, new RecordItemIndex(30));
            repo.ComPentairPentairhome.Container22475EMunozStQueenCreek.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(31));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.ChangeAddressContinue' at Center", repo.ComPentairPentairhome.ChangeAddressContinueInfo, new RecordItemIndex(32));
            repo.ComPentairPentairhome.ChangeAddressContinue.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(33));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.AddressUpdatedOK' at Center", repo.ComPentairPentairhome.AddressUpdatedOKInfo, new RecordItemIndex(34));
            repo.ComPentairPentairhome.AddressUpdatedOK.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(35));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
